CREATE TABLE technology
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_technology PRIMARY KEY (id)
);

CREATE TABLE users
(
    deleted_at BOOLEAN      NOT NULL,
    id         UUID         NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE vacancies
(
    id          UUID NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    title       VARCHAR(255),
    description VARCHAR(255),
    company     VARCHAR(255),
    status      VARCHAR(255),
    url         VARCHAR(255),
    user_id     UUID NOT NULL,
    CONSTRAINT pk_vacancies PRIMARY KEY (id)
);

CREATE TABLE vacancy_technology
(
    technology_id BIGINT NOT NULL,
    vacancy_id    UUID   NOT NULL,
    CONSTRAINT pk_vacancy_technology PRIMARY KEY (technology_id, vacancy_id)
);

ALTER TABLE technology
    ADD CONSTRAINT uc_technology_name UNIQUE (name);

ALTER TABLE vacancies
    ADD CONSTRAINT FK_VACANCIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE vacancy_technology
    ADD CONSTRAINT fk_vactec_on_technology_entity FOREIGN KEY (technology_id) REFERENCES technology (id);

ALTER TABLE vacancy_technology
    ADD CONSTRAINT fk_vactec_on_vacancy_entity FOREIGN KEY (vacancy_id) REFERENCES vacancies (id);